// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4XJZriXzrUmtsmK8jwabA6kxAFpRaEjI',
    appId: '1:229813459102:web:1c5da33d73d91fbd9e038f',
    messagingSenderId: '229813459102',
    projectId: 'constrationapp-7b41c',
    authDomain: 'constrationapp-7b41c.firebaseapp.com',
    storageBucket: 'constrationapp-7b41c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtwxtwnTafz02sUI80Kpm7lSQme84Bxlw',
    appId: '1:229813459102:android:9a7aa673ddce9f189e038f',
    messagingSenderId: '229813459102',
    projectId: 'constrationapp-7b41c',
    storageBucket: 'constrationapp-7b41c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7Vyiv5Erm6g4HNNfruPS07bS_3lIqiXU',
    appId: '1:229813459102:ios:f242a901155c27659e038f',
    messagingSenderId: '229813459102',
    projectId: 'constrationapp-7b41c',
    storageBucket: 'constrationapp-7b41c.appspot.com',
    iosBundleId: 'com.example.constructionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7Vyiv5Erm6g4HNNfruPS07bS_3lIqiXU',
    appId: '1:229813459102:ios:12f8ba4a5c19c46b9e038f',
    messagingSenderId: '229813459102',
    projectId: 'constrationapp-7b41c',
    storageBucket: 'constrationapp-7b41c.appspot.com',
    iosBundleId: 'com.example.constructionApp.RunnerTests',
  );
}
